action.yml: Configurable reviewdog reporter
Signed-off-by: Nils Wistoff <nwistoff@iis.ee.ethz.ch>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -20,6 +20,9 @@ inputs:
     description: 'If there are any formatting issues in the codebase, the action will return with an error'
     required: false
     default: 'false'
+  reviewdog_fail_on_error:
+    description: 'Fail the action when rule violations are found'
+    default: 'false'
   verible_version:
     description: 'Use selected Verible version (defaults to latest release)'
     default: 'latest'
@@ -89,19 +92,17 @@ runs:
         git stash
         echo "# --- "
 
-        if [ "${{ github.event_name }}" == "pull_request" ] || [ "${{ github.event_name }}" == "pull_request_target" ]; then
-          echo "### Run reviewdog ###"
-          echo "---------------------"
-          export REVIEWDOG_GITHUB_API_TOKEN="${{ inputs.github_token }}"
-          echo "running reviewdog"
-          reviewdog -name="verible-verilog-format" \
-          -f=diff -f.diff.strip=1 \
-          -reporter="${{ inputs.reviewdog_reporter }}" \
-          -filter-mode="diff_context" \
-          -level="info" \
-          -diff="$diff_cmd" \
-          -fail-on-error="false" <vvf_git_diff.log || true
-        fi
+        echo "### Run reviewdog ###"
+        echo "---------------------"
+        export REVIEWDOG_GITHUB_API_TOKEN="${{ inputs.github_token }}"
+        echo "running reviewdog"
+        reviewdog -name="verible-verilog-format" \
+        -f=diff -f.diff.strip=1 \
+        -reporter="${{ inputs.reviewdog_reporter }}" \
+        -filter-mode="diff_context" \
+        -level="info" \
+        -diff="$diff_cmd" \
+        -fail-on-error="${{ inputs.reviewdog_fail_on_error }}" <vvf_git_diff.log || true
 
         if [ "${{ inputs.fail_on_formatting_suggestions }}" == "true" ]; then
             if [[ -s "vvf_git_diff.log" || -s "vvf_err.log" ]]; then
